name: squiggly
description: A Dart analyzer plugin that provides custom linting rules and code analysis for Dart projects.
version: 1.0.0
repository: https://github.com/KlausJokisuo/squiggly
issue_tracker: https://github.com/KlausJokisuo/squiggly/issues

environment:
  sdk: ^3.10.0


dependencies:
  analysis_server_plugin: ^0.3.4
  analyzer: ^9.0.0
  analyzer_plugin: ^0.13.11
  meta: ^1.17.0


dev_dependencies:
  lints: ^6.0.0
  analyzer_testing: ^0.1.7
  test_reflective_loader: ^0.4.0
  coverage: ^1.15.0
  test: ^1.28.0
